services:
  build:
    build: .
    image: obsidian-local-web-page-viewer-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev
    tty: true

volumes:
  node_modules:
